window.GALLERIES={
  "osa-1":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/0/04/Aleksandrovskiy_Tsentral_(Old_Russian_Prison).jpg","caption":"Александровский централ, начало XX века · Public Domain","sourceUrl":"https://commons.wikimedia.org/wiki/File:Aleksandrovskiy_Tsentral_(Old_Russian_Prison).jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/f/f8/Alexandrofski_central_prison_about_sixty_versts_from_Irkutsk_LCCN99615472.jpg","thumb":"assets/place-photos/gallery-6f2c061faf75.jpg","caption":"Александровский централ, 1885 · Library of Congress","sourceUrl":"https://commons.wikimedia.org/wiki/File:Alexandrofski_central_prison_about_sixty_versts_from_Irkutsk_LCCN99615472.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/b/b9/Through_Siberia_(1883)._The_Alexandreffsky_Central_Prison,_near_Irkutsk.jpg","thumb":"assets/place-photos/gallery-ad1850086c81.jpg","caption":"Александровский централ в издании 1883 года · Public Domain","sourceUrl":"https://commons.wikimedia.org/wiki/File:Through_Siberia_(1883)._The_Alexandreffsky_Central_Prison,_near_Irkutsk.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/a/a5/Side-lights_on_Siberia_(1898),_page_210,_Inside_the_courtyard.jpg","caption":"Внутренний двор Александровского централа, публикация 1898 года · Public Domain","sourceUrl":"https://commons.wikimedia.org/wiki/File:Side-lights_on_Siberia_(1898),_page_210,_Inside_the_courtyard.jpg"}
  ],
  "osa-4":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Vershina_view_AB.jpg","thumb":"assets/place-photos/osa-4-1.jpg","caption":"Вершина · фото Andrzej Barabasz (Chepry) · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Vershina_view_AB.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/4/4e/Wierszyna,_ko%C5%9Bci%C3%B3%C5%82ek_katolicki_2013.jpg","thumb":"assets/place-photos/osa-4-2.jpg","caption":"Костёл в Вершине · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Wierszyna,_ko%C5%9Bci%C3%B3%C5%82ek_katolicki_2013.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/c/c9/Ko%C5%9Bci%C3%B3%C5%82_we_wsi_Wierszyna.jpg","thumb":"assets/place-photos/osa-4-3.jpg","caption":"Костёл и деревенская среда Вершины · фото W0zny · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Ko%C5%9Bci%C3%B3%C5%82_we_wsi_Wierszyna.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/9/91/Wn%C4%99trze_chaty_w_skansenie_we_wsi_Wierszyna.jpg","thumb":"assets/place-photos/osa-4-4.jpg","caption":"Интерьер традиционной избы в скансене Вершины · фото W0zny · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Wn%C4%99trze_chaty_w_skansenie_we_wsi_Wierszyna.jpg"}
  ],
  "osa-5":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/4/4e/Wierszyna,_ko%C5%9Bci%C3%B3%C5%82ek_katolicki_2013.jpg","thumb":"assets/place-photos/osa-4-2.jpg","caption":"Костёл Св. Станислава в Вершине · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Wierszyna,_ko%C5%9Bci%C3%B3%C5%82ek_katolicki_2013.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/c/c9/Ko%C5%9Bci%C3%B3%C5%82_we_wsi_Wierszyna.jpg","thumb":"assets/place-photos/osa-4-3.jpg","caption":"Костёл Св. Станислава · фото W0zny · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Ko%C5%9Bci%C3%B3%C5%82_we_wsi_Wierszyna.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/6/69/Ko%C5%9Bci%C3%B3%C5%82_we_wsi_Wierszyna,_elewaja_frontowa.jpg","thumb":"assets/place-photos/gallery-e1d76d9c1377.jpg","caption":"Фасад костёла в Вершине · Wikimedia Commons","sourceUrl":"https://commons.wikimedia.org/wiki/File:Ko%C5%9Bci%C3%B3%C5%82_we_wsi_Wierszyna,_elewaja_frontowa.jpg"}
  ],
  "osa-6":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/9/91/Wn%C4%99trze_chaty_w_skansenie_we_wsi_Wierszyna.jpg","thumb":"assets/place-photos/osa-4-4.jpg","caption":"Интерьер традиционной избы в скансене Вершины · фото W0zny · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Wn%C4%99trze_chaty_w_skansenie_we_wsi_Wierszyna.jpg"}
  ]
};
Object.assign(window.GALLERIES,{
  "arshan-1":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/1/12/%D0%90%D1%80%D1%88%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%B2%D0%BE%D0%B4%D0%BE%D0%BF%D0%B0%D0%B4.jpg","caption":"Первый водопад на Кынгарге · IrinaChernoyarova · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Аршанский_водопад.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/8/8b/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2%D0%BE%D0%B4%D0%BE%D0%BF%D0%B0%D0%B4_,_%D1%80._%D0%9A%D1%8B%D0%BD%D0%B3%D1%8B%D1%80%D0%B3%D0%B0.jpg","thumb":"assets/place-photos/gallery-e1f6cc377864.jpg","caption":"Первый водопад на Кынгарге · Zhmurova91 · Wikimedia Commons","sourceUrl":"https://commons.wikimedia.org/wiki/File:Первый_водопад_,_р._Кынгырга.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/b/b1/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2%D0%BE%D0%B4%D0%BE%D0%BF%D0%B0%D0%B4.jpg","thumb":"assets/place-photos/gallery-458f739e3ad7.jpg","caption":"Первый водопад · Zhmurova91 · Wikimedia Commons","sourceUrl":"https://commons.wikimedia.org/wiki/File:Первый_водопад.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/5/5f/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2%D0%BE%D0%B4%D0%BE%D0%BF%D0%B0%D0%B4,_%D1%80._%D0%9A%D1%8B%D0%BD%D0%B3%D1%8B%D1%80%D0%B3%D0%B0.jpg","thumb":"assets/place-photos/gallery-9a77c024b7bf.jpg","caption":"Первый водопад на Кынгарге · Zhmurova91 · Wikimedia Commons","sourceUrl":"https://commons.wikimedia.org/wiki/File:Первый_водопад,_р._Кынгырга.jpg"}
  ],
  "arshan-2":[{"src":"https://upload.wikimedia.org/wikipedia/commons/d/d5/Buddha_of_Medicine_in_Arshan.jpg","thumb":"assets/place-photos/gallery-36762a418374.jpg","caption":"Будда Медицины · Andrijko Z. · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Buddha_of_Medicine_in_Arshan.jpg"}],
  "arshan-3":[{"src":"https://upload.wikimedia.org/wikipedia/commons/5/5a/Khoymorsky_datsan_near_Arshan_%28Buryatia%29.jpg","caption":"Хойморский дацан «Бодхидхарма» · Tohuchar · Wikimedia Commons","sourceUrl":"https://commons.wikimedia.org/wiki/File:Khoymorsky_datsan_near_Arshan_(Buryatia).jpg"}],
  "arshan-5":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/b/ba/%D0%9D%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0_%D0%9F%D1%83%D1%81%D1%82%D1%8B%D0%BD%D1%8C.jpg","thumb":"assets/place-photos/gallery-5bdbb4090f92.jpg","caption":"Источник Нилова Пустынь · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Нилова_Пустынь.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/5/5c/%D0%9D%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0_%D0%BF%D1%83%D1%81%D1%82%D1%8B%D0%BD%D1%8C._%D0%92%D0%B8%D0%B4_%D1%81_%D0%BB%D1%83%D0%B3%D0%BE%D0%B2_%D0%BD%D0%B0_%D1%86%D0%B5%D1%80%D0%BA%D0%BE%D0%B2%D1%8C_%D0%B8_%D0%B4%D0%BE%D0%BC,_%D0%B2%D1%8B%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5_%D0%B0%D1%80%D1%85%D0%B8%D0%B5%D1%80%D0%B5%D0%B5%D0%BC_%D0%9D%D0%B8%D0%BB%D0%BE%D0%BC.jpg","caption":"Исторический вид Ниловой Пустыни · CC0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Нилова_пустынь._Вид_с_лугов_на_церковь_и_дом,_выстроенные_архиереем_Нилом.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/f/f7/%D0%9D%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0_%D0%BF%D1%83%D1%81%D1%82%D1%8B%D0%BD%D1%8C._%D0%92%D0%B8%D0%B4_%D1%81_%D0%B2%D0%BE%D0%B7%D0%B2%D1%8B%D1%88%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BD%D0%B0_%D1%80._%D0%95%D1%85%D1%8D-%D0%A3%D0%B3%D1%83%D0%BD.jpg","caption":"Нилова Пустынь и долина Ехэ-Угун · CC0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Нилова_пустынь._Вид_с_возвышения_на_р._Ехэ-Угун.jpg"}
  ],
  "slud-1":[
    {"src":"https://upload.wikimedia.org/wikipedia/commons/5/5e/Slyudyanka_train_station.jpg","thumb":"assets/place-photos/slud-1-1.jpg","caption":"Мраморный вокзал Слюдянки · Honza Soukup · CC BY 2.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Slyudyanka_train_station.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/6/62/Slyudyanka_station.jpg","thumb":"assets/place-photos/slud-1-2.jpg","caption":"Вокзал Слюдянки · Public Domain","sourceUrl":"https://commons.wikimedia.org/wiki/File:Slyudyanka_station.jpg"},
    {"src":"https://upload.wikimedia.org/wikipedia/commons/e/e0/%D0%91%D0%B0%D0%B9%D0%BA%D0%B0%D0%BB._%D0%92%D0%BE%D0%BA%D0%B7%D0%B0%D0%BB_%D1%81%D1%82.%D0%A1%D0%BB%D1%8E%D0%B4%D1%8F%D0%BD%D0%BA%D0%B0_%D1%81_%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D0%BE%D0%B9_%D0%B8%D0%BD%D0%B6%D0%B5%D0%BD%D0%B5%D1%80%D0%BE%D0%B2._(%D0%B0%D0%BB%D1%8C%D0%B1.%D0%9C%D0%9F%D0%A1._%D0%90%D0%BB%D1%8C%D0%B1%D0%BE%D0%BC%D1%8A_%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BA%D1%8A_%D0%B8_%D0%B2%D0%B8%D0%B4%D0%BE%D0%B2%D1%8A_%D0%9A%D1%80%D1%83%D0%B3%D0%BE%D0%B1%D0%B0%D0%B9%D0%BA%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B9_%D0%B6.%D0%B4.1900-1904%D0%B3)_1901-1904%D0%B3_%D0%93%D0%98%D0%9C_e1.jpg","thumb":"assets/place-photos/slud-1-3.jpg","caption":"Вокзал Слюдянки около 1904 года · Public Domain","sourceUrl":"https://commons.wikimedia.org/wiki/File:Байкал._Вокзал_ст.Слюдянка_с_группой_инженеров._(альб.МПС._Альбомъ_построекъ_и_видовъ_Кругобайкальской_ж.д.1900-1904г)_1901-1904г_ГИМ_e1.jpg"}
  ],
  "slud-8":[{"src":"https://upload.wikimedia.org/wikipedia/commons/a/a1/Slyudyanka,_from_Lake_Baikal.jpg","thumb":"assets/place-photos/gallery-99794f7478fc.jpg","caption":"Слюдянка со стороны Байкала · Honza Soukup · CC BY 2.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Slyudyanka,_from_Lake_Baikal.jpg"}],
  "slud-13":[{"src":"https://upload.wikimedia.org/wikipedia/commons/4/4c/%D0%91%D0%B0%D0%B9%D0%BA%D0%B0%D0%BB%D1%8C%D1%81%D0%BA,_%D0%B1%D0%B5%D1%80%D0%B5%D0%B3_%D0%91%D0%B0%D0%B9%D0%BA%D0%B0%D0%BB%D0%B0.jpg","thumb":"assets/place-photos/gallery-41f282f0fd48.jpg","caption":"Берег Байкала в Байкальске · SAKRI · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Байкальск,_берег_Байкала.jpg"}],
  "slud-15":[{"src":"https://upload.wikimedia.org/wikipedia/commons/6/65/%D0%9A%D0%BB%D1%83%D0%B1%D0%BD%D0%B8%D0%BA%D0%B0_-_%D0%BE%D0%B4%D0%B8%D0%BD_%D0%B8%D0%B7_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2_%D0%91%D0%B0%D0%B9%D0%BA%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B0.jpg","thumb":"assets/place-photos/gallery-b027761f8cf9.jpg","caption":"Клубника — один из символов Байкальска · Миллер Наталья · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Клубника_-_один_из_символов_Байкальска.jpg"}]
});
Object.assign(window.GALLERIES,{
  "arshan-15":[{"src":"https://upload.wikimedia.org/wikipedia/commons/1/11/Siberian_Solar_Radio_Telescope.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-15-1.jpg","caption":"Радиоастрофизическая обсерватория «Бадары» · IvanT67 · CC0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Siberian_Solar_Radio_Telescope.jpg"}],
  "arshan-16":[{"src":"https://upload.wikimedia.org/wikipedia/commons/6/66/Pool_%28Zhemchug%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-16-1.jpg","caption":"Бассейн с минеральной водой, Жемчуг · Аркадий Зарубин · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Pool_(Zhemchug).jpg"}]
});
Object.assign(window.GALLERIES,{"arshan-6":[{"src":"https://upload.wikimedia.org/wikipedia/commons/7/75/Burkhan_Babay_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-6-1.jpg","caption":"Бурхан Баабай · Аркадий Зарубин · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Burkhan_Babay_01.jpg"},{"src":"https://upload.wikimedia.org/wikipedia/commons/4/4f/Burkhan_Babay_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-6-2.jpg","caption":"Бурхан Баабай · Аркадий Зарубин · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Burkhan_Babay_02.jpg"},{"src":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Burkhan_Babay_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-6-3.jpg","caption":"Бурхан Баабай · Аркадий Зарубин · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Burkhan_Babay_03.jpg"}],"arshan-7":[{"src":"https://upload.wikimedia.org/wikipedia/commons/f/fe/Hubun_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-7-1.jpg","caption":"Минеральный источник Хубун · Аркадий Зарубин · CC BY-SA 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Hubun_(2).jpg"}],"arshan-8":[{"src":"https://upload.wikimedia.org/wikipedia/commons/3/3a/Arshan_park_area.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","thumb":"assets/place-photos/arshan-8-1.jpg","caption":"Курортный парк Аршана · TatyanaPenn · CC BY 3.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Arshan_park_area.jpg"}]});
Object.assign(window.GALLERIES,{"arshan-18":[{"src":"https://upload.wikimedia.org/wikipedia/commons/a/a7/%D0%9F%D0%BE%D1%82%D1%83%D1%85%D1%88%D0%B8%D0%B9_%D0%B2%D1%83%D0%BB%D0%BA%D0%B0%D0%BD_%D0%A2%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%BD%D0%B0.jpg","thumb":"assets/place-photos/arshan-18-1.jpg","caption":"Тальская вершина · Buyanto Gyrgenov · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:%D0%9F%D0%BE%D1%82%D1%83%D1%85%D1%88%D0%B8%D0%B9_%D0%B2%D1%83%D0%BB%D0%BA%D0%B0%D0%BD_%D0%A2%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%BD%D0%B0.jpg"}]});
Object.assign(window.GALLERIES,{"slud-3":[{"src":"https://upload.wikimedia.org/wikipedia/commons/5/59/Shaman_Cape_on_Lake_Baikal.jpg","thumb":"assets/place-photos/slud-3-1.jpg","caption":"Шаманский мыс · JukoFF · CC BY-SA 4.0","sourceUrl":"https://commons.wikimedia.org/wiki/File:Shaman_Cape_on_Lake_Baikal.jpg"}]});
